import {
  applyActivityFilters,
  buildActivitySummary,
  groupActivityEntriesByDay,
  mergeActivityEntries,
  type ActivityEntry,
  type ActivityQuery,
  type RecentActivity,
} from "./read-model";

/**
 * Read-only demo activity feed. Used when Supabase is not configured (local
 * preview) or when no real activity exists yet, so the Activity page renders a
 * populated, plain-English BSR audit trail instead of an empty state. Every
 * entry is display-only; nothing here triggers an outbound action.
 */

const MIN = 60_000;
const HOUR = 3_600_000;
const DAY = 86_400_000;

function iso(offsetMs: number): string {
  return new Date(Date.now() - offsetMs).toISOString();
}

type Seed = Omit<ActivityEntry, "occurredAt"> & { agoMs: number };

const SEEDS: Seed[] = [
  {
    id: "demo-act-1",
    kind: "draft",
    tone: "amber",
    title: "Generated 3 campaign concepts",
    detail: "Emergency Water Response 2026 — 3 angles drafted for review",
    actor: "Arc",
    actorType: "arc",
    category: "asset",
    insightLabel: "Needs review",
    relatedLabel: "Emergency Water Response 2026",
    href: "/campaigns",
    agoMs: 22 * MIN,
  },
  {
    id: "demo-act-2",
    kind: "campaign",
    tone: "green",
    title: "Campaign approved",
    detail: "Spring Storm Prep 2026 brief approved and locked for build",
    actor: "Evan",
    actorType: "human",
    category: "campaign",
    insightLabel: "Marketing progress",
    relatedLabel: "Spring Storm Prep 2026",
    href: "/campaigns",
    agoMs: 48 * MIN,
  },
  {
    id: "demo-act-3",
    kind: "event",
    tone: "blue",
    title: "Lead updated",
    detail: "Northwest Property Group moved to Qualified — lead score 88",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Customer signal",
    relatedLabel: "Northwest Property Group",
    href: "/crm/leads",
    agoMs: 1 * HOUR + 5 * MIN,
  },
  {
    id: "demo-act-4",
    kind: "run",
    tone: "green",
    title: "Run completed",
    detail: "Creative generation for Spring Storm Prep — 6 of 9 variants",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Agent task",
    href: "/board",
    agoMs: 1 * HOUR + 32 * MIN,
  },
  {
    id: "demo-act-5",
    kind: "draft",
    tone: "amber",
    title: "Persona insight added",
    detail: "Property Manager segment shows rising winter-burst urgency",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Property Manager",
    href: "/personas",
    agoMs: 2 * HOUR + 10 * MIN,
  },
  {
    id: "demo-act-6",
    kind: "draft",
    tone: "red",
    title: "Integrity finding raised",
    detail: "Claim-language risk flagged in Emergency Water ad headline",
    actor: "Arc",
    actorType: "arc",
    category: "risk",
    insightLabel: "Risk blocked",
    relatedLabel: "Emergency Water Response 2026",
    href: "/board",
    agoMs: 2 * HOUR + 40 * MIN,
  },
  {
    id: "demo-act-7",
    kind: "draft",
    tone: "amber",
    title: "Asset created",
    detail: "Fire & Smoke Rebuild landing one-pager copy drafted",
    actor: "Arc",
    actorType: "arc",
    category: "asset",
    insightLabel: "Needs review",
    relatedLabel: "Fire & Smoke Rebuild",
    href: "/campaigns",
    agoMs: 3 * HOUR + 15 * MIN,
  },
  {
    id: "demo-act-8",
    kind: "campaign",
    tone: "red",
    title: "Approval Declined",
    detail: "Mold Awareness SMS declined — tone too aggressive, revise CTA",
    actor: "Evan",
    actorType: "human",
    category: "campaign",
    insightLabel: "Risk blocked",
    relatedLabel: "Mold Remediation Awareness",
    href: "/campaigns",
    agoMs: 4 * HOUR,
  },
  {
    id: "demo-act-9",
    kind: "draft",
    tone: "amber",
    title: "Revision requested",
    detail: "Property Manager email batch — soften urgency, add proof point",
    actor: "Evan",
    actorType: "human",
    category: "approval",
    insightLabel: "Needs review",
    relatedLabel: "Property Manager Reactivation",
    href: "/approvals",
    agoMs: 4 * HOUR + 50 * MIN,
  },
  {
    id: "demo-act-10",
    kind: "event",
    tone: "blue",
    title: "Company added",
    detail: "Lakeview Plumbing flagged as high-fit referral partner (ZIP 60618)",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Customer signal",
    relatedLabel: "Lakeview Plumbing",
    href: "/crm/companies",
    agoMs: 6 * HOUR,
  },
  {
    id: "demo-act-11",
    kind: "run",
    tone: "blue",
    title: "Run started",
    detail: "Message-angle research for Insurance Agent Co-Marketing",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Agent task",
    href: "/board",
    agoMs: 7 * HOUR,
  },
  {
    id: "demo-act-12",
    kind: "event",
    tone: "blue",
    title: "Weather signal received",
    detail: "Freeze warning issued for Cook County — preventative demand likely",
    actor: "Weather Integration",
    actorType: "integration",
    category: "integration",
    insightLabel: "Customer signal",
    relatedLabel: "Cook County",
    href: null,
    agoMs: 9 * HOUR,
  },
  {
    id: "demo-act-13",
    kind: "campaign",
    tone: "green",
    title: "Campaign package approved",
    detail: "Emergency Water Response launch package approved and outbound-locked",
    actor: "Evan",
    actorType: "human",
    category: "campaign",
    insightLabel: "Marketing progress",
    relatedLabel: "Emergency Water Response 2026",
    href: "/campaigns",
    agoMs: 1 * DAY + 1 * HOUR,
  },
  {
    id: "demo-act-14",
    kind: "draft",
    tone: "green",
    title: "Asset approved",
    detail: "GC / remodeler partner referral sheet approved for distribution prep",
    actor: "Evan",
    actorType: "human",
    category: "asset",
    insightLabel: "Marketing progress",
    relatedLabel: "GC Remodeler Partnerships",
    href: "/campaigns",
    agoMs: 1 * DAY + 3 * HOUR,
  },
  {
    id: "demo-act-15",
    kind: "event",
    tone: "blue",
    title: "Contact updated",
    detail: "Jordan Reyes (Ops Manager) confirmed as referral decision-maker",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Customer signal",
    relatedLabel: "Jordan Reyes",
    href: "/crm/contacts",
    agoMs: 1 * DAY + 5 * HOUR,
  },
  {
    id: "demo-act-16",
    kind: "run",
    tone: "green",
    title: "Run completed",
    detail: "Spring Storm Prep brief + audience plan generated",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Agent task",
    href: "/board",
    agoMs: 1 * DAY + 6 * HOUR,
  },
  {
    id: "demo-act-17",
    kind: "draft",
    tone: "amber",
    title: "Opportunity surfaced",
    detail: "12 dormant landlord accounts flagged for re-engagement",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Needs review",
    relatedLabel: "Landlord segment",
    href: "/personas",
    agoMs: 1 * DAY + 9 * HOUR,
  },
  {
    id: "demo-act-18",
    kind: "campaign",
    tone: "amber",
    title: "Campaign submitted",
    detail: "Listing Agent Pre-Sale moisture inspection offer submitted for review",
    actor: "Arc",
    actorType: "arc",
    category: "campaign",
    insightLabel: "Needs review",
    relatedLabel: "Listing Agent Pre-Sale",
    href: "/campaigns",
    agoMs: 2 * DAY,
  },
  {
    id: "demo-act-19",
    kind: "event",
    tone: "blue",
    title: "Outcome recorded",
    detail: "Q1 water-loss campaign booked 14 jobs — attribution logged",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Campaign result",
    relatedLabel: "Q1 Water Loss",
    href: "/crm/outcomes",
    agoMs: 2 * DAY + 4 * HOUR,
  },
  {
    id: "demo-act-20",
    kind: "run",
    tone: "gray",
    title: "Heartbeat logged",
    detail: "Arc runner healthy — outbound actions remain locked",
    actor: "System",
    actorType: "system",
    category: "system",
    insightLabel: null,
    relatedLabel: "Arc runner",
    href: null,
    agoMs: 2 * DAY + 8 * HOUR,
  },
];

export function buildDemoActivity(query: ActivityQuery = {}): RecentActivity {
  const entries: ActivityEntry[] = SEEDS.map(({ agoMs, ...rest }) => ({ ...rest, occurredAt: iso(agoMs) }));
  const filtered = applyActivityFilters(entries, query);
  const merged = mergeActivityEntries(filtered, query.limit ?? 100);

  return {
    status: "live",
    entries: merged,
    summary: buildActivitySummary(merged),
    groups: groupActivityEntriesByDay(merged),
  };
}
