// Offline preview fixtures for the Outbox (ARC_DEMO_DATA=1). Mirrors a realistic
// send queue across the dispatch lifecycle so the backend-less preview renders a
// populated console instead of an empty one. Illustrative sample content for a
// demo tenant — no real recipients, no real send.

import type { DispatchView } from "./status";

export function buildDemoDispatches(): DispatchView[] {
  return [
    {
      id: "demo-dispatch-email-queued",
      campaignId: "demo-campaign-storm",
      campaignName: "Storm Rapid Response",
      assetId: "demo-asset-email",
      deliverable: "Inspection follow-up email",
      channel: "email",
      status: "queued",
      scheduledFor: null,
      dispatchedAt: null,
      recipientSummary: "64 insured · fresh-damage homes",
      audienceCount: 64,
      resultNote: null,
      updatedAt: "Today 9:42 AM",
    },
    {
      id: "demo-dispatch-sms-queued",
      campaignId: "demo-campaign-storm",
      campaignName: "Storm Rapid Response",
      assetId: "demo-asset-sms",
      deliverable: "Warm inspection check-in (SMS)",
      channel: "sms",
      status: "queued",
      scheduledFor: null,
      dispatchedAt: null,
      recipientSummary: "142-home priority segment",
      audienceCount: 142,
      resultNote: null,
      updatedAt: "Today 9:41 AM",
    },
    {
      id: "demo-dispatch-email-scheduled",
      campaignId: "demo-campaign-maintenance",
      campaignName: "Spring Maintenance Reminder",
      assetId: "demo-asset-maint",
      deliverable: "Seasonal roof check reminder",
      channel: "email",
      status: "scheduled",
      scheduledFor: "Tomorrow 8:00 AM",
      dispatchedAt: null,
      recipientSummary: "past customers · 12+ months",
      audienceCount: 318,
      resultNote: null,
      updatedAt: "Today 8:05 AM",
    },
    {
      id: "demo-dispatch-email-sent",
      campaignId: "demo-campaign-referral",
      campaignName: "Referral Thank-You",
      assetId: "demo-asset-referral",
      deliverable: "Thank-you + review request",
      channel: "email",
      status: "sent",
      scheduledFor: null,
      dispatchedAt: "Today 7:30 AM",
      recipientSummary: "recently completed jobs",
      audienceCount: 41,
      resultNote: "Sent via Resend",
      updatedAt: "Today 7:30 AM",
    },
    {
      id: "demo-dispatch-email-delivered",
      campaignId: "demo-campaign-storm",
      campaignName: "Storm Rapid Response",
      assetId: "demo-asset-awareness",
      deliverable: "Storm awareness announcement",
      channel: "email",
      status: "delivered",
      scheduledFor: null,
      dispatchedAt: "Yesterday 4:15 PM",
      recipientSummary: "storm-zone homeowners",
      audienceCount: 206,
      resultNote: "204 delivered · 2 bounced",
      updatedAt: "Yesterday 4:20 PM",
    },
    {
      id: "demo-dispatch-email-failed",
      campaignId: "demo-campaign-adjuster",
      campaignName: "Adjuster Follow-ups",
      assetId: "demo-asset-adjuster",
      deliverable: "Claim coordination note",
      channel: "email",
      status: "failed",
      scheduledFor: null,
      dispatchedAt: "Yesterday 2:02 PM",
      recipientSummary: "open-claim contacts",
      audienceCount: 9,
      resultNote: "Provider rejected: sender domain not verified",
      updatedAt: "Yesterday 2:03 PM",
    },
  ];
}
