// Offline preview fixtures for the Outbox (ARC_DEMO_DATA=1). Mirrors a realistic
// send queue across the dispatch lifecycle so the backend-less preview renders a
// populated console instead of an empty one. Illustrative sample content for a
// demo tenant — no real recipients, no real send.

import type { DispatchView } from "./status";

export function buildDemoDispatches(): DispatchView[] {
  return [
    {
      id: "demo-dispatch-email-queued",
      campaignId: "demo-campaign-storm",
      campaignName: "Pricing-Intent Fast Track",
      assetId: "demo-asset-email",
      deliverable: "Walkthrough follow-up email",
      channel: "email",
      status: "queued",
      scheduledFor: null,
      dispatchedAt: null,
      recipientSummary: "64 active-trial · high-intent accounts",
      audienceCount: 64,
      resultNote: null,
      updatedAt: "Today 9:42 AM",
      preview: {
        to: "64-account active-trial segment",
        subject: "You looked at pricing — here’s a walkthrough",
        text: "Hi {{first_name}}, we noticed your team spent time on our pricing page this week. We’re offering a free, no-pressure walkthrough this week.",
      },
    },
    {
      id: "demo-dispatch-sms-queued",
      campaignId: "demo-campaign-storm",
      campaignName: "Pricing-Intent Fast Track",
      assetId: "demo-asset-sms",
      deliverable: "Warm walkthrough check-in (SMS)",
      channel: "sms",
      status: "queued",
      scheduledFor: null,
      dispatchedAt: null,
      recipientSummary: "142-account priority segment",
      audienceCount: 142,
      resultNote: null,
      updatedAt: "Today 9:41 AM",
      preview: {
        to: "142-account priority segment",
        subject: null,
        text: "Still comparing options? Reply DEMO and we’ll set up a quick, no-pressure walkthrough.",
      },
    },
    {
      id: "demo-dispatch-email-scheduled",
      campaignId: "demo-campaign-maintenance",
      campaignName: "Quarterly Check-in",
      assetId: "demo-asset-maint",
      deliverable: "Quarterly usage check-in",
      channel: "email",
      status: "scheduled",
      scheduledFor: "Tomorrow 8:00 AM",
      dispatchedAt: null,
      recipientSummary: "past customers · 12+ months",
      audienceCount: 318,
      resultNote: null,
      updatedAt: "Today 8:05 AM",
      preview: {
        to: "past customers · 12+ months",
        subject: "A quick quarterly account check-in",
        text: "A short quarterly check-in can surface small adoption gaps before they slow your team down.",
      },
    },
    {
      id: "demo-dispatch-email-sent",
      campaignId: "demo-campaign-referral",
      campaignName: "Referral Thank-You",
      assetId: "demo-asset-referral",
      deliverable: "Thank-you + review request",
      channel: "email",
      status: "sent",
      scheduledFor: null,
      dispatchedAt: "Today 7:30 AM",
      recipientSummary: "recently onboarded accounts",
      audienceCount: 41,
      resultNote: "Sent via Resend",
      updatedAt: "Today 7:30 AM",
      preview: null,
    },
    {
      id: "demo-dispatch-email-delivered",
      campaignId: "demo-campaign-storm",
      campaignName: "Pricing-Intent Fast Track",
      assetId: "demo-asset-awareness",
      deliverable: "Product update announcement",
      channel: "email",
      status: "delivered",
      scheduledFor: null,
      dispatchedAt: "Yesterday 4:15 PM",
      recipientSummary: "high-intent accounts",
      audienceCount: 206,
      resultNote: "204 delivered · 2 bounced",
      updatedAt: "Yesterday 4:20 PM",
      preview: null,
    },
    {
      id: "demo-dispatch-email-failed",
      campaignId: "demo-campaign-adjuster",
      campaignName: "Procurement Follow-ups",
      assetId: "demo-asset-adjuster",
      deliverable: "Procurement coordination note",
      channel: "email",
      status: "failed",
      scheduledFor: null,
      dispatchedAt: "Yesterday 2:02 PM",
      recipientSummary: "open-evaluation contacts",
      audienceCount: 9,
      resultNote: "Provider rejected: sender domain not verified",
      updatedAt: "Yesterday 2:03 PM",
      preview: {
        to: "open-evaluation contacts",
        subject: "Procurement coordination update",
        text: "Here is the latest coordination update for your open evaluation.",
      },
    },
  ];
}
